### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by edurguti** [cetteup/successfactors-req-id-lookup#1]
Anyway to find the     "jobID": 634239700, if I know the career_job_req_id?

**Comment by cetteup** [comment]
So you want to map the RCM `career_job_req_id` to the corresponding RMK job id?

I know two ways to do this:
1. Use the `career_job_req_id` as job search keyword (either [on the RMK site directly](https://jobs.sap.com/search/?q=355088), or [via the RSS feed](https://jobs.sap.com/services/rss/job/?locale=en_US&keywords=(355088))). Either way should only return a single result, but there's no way to be sure without knowing the internal implementation SAP use for the keyword search. If you receive multiple results or want to be sure, you can resolve the job ID back and see of you get the req id you initially put in.
2. Use a job invite link to the RMK site, e.g. https://jobs.sap.com/job-invite/355088/ (355088 is the `career_job_req_id`). Those links redirect you to the correct job on the RMK site, which then contains the job id both in the URL and the HTML.

Both ways are easily automated, either by fetching and parsing the RSS feed or by fetching the job invite link without following redirects.

**Comment by edurguti** [comment]
I ended up using the rmk site directly and searched for career_job_req_id.
Used beatifulsoup in python to find the joblink url and parsed out the
jobID. Thanks for the pointers.

**Comment by edurguti** [comment]
Actually this is safer in python
```
import requests

r = "https://jobs.sap.com/job-invite/203333/"
page = requests.get(r)
# parse out the last
print(page.url.split("/")[-2])
```
gives out the ID
